SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE(F_VALIDA_CONTRATO(17, 'B')); -- Esperado: PLANO PLUS
  DBMS_OUTPUT.PUT_LINE(F_VALIDA_CONTRATO(35, 'A')); -- Esperado: PLANO EXECUTIVO
  DBMS_OUTPUT.PUT_LINE(F_VALIDA_CONTRATO(70, 'B')); -- Esperado: PLANO OURO
END;
/
   

SELECT F_VALIDA_CONTRATO(25, 'A') FROM DUAL;
